name: "words"

preprocessor:
  normalize:
    mean:
    - 0.5
    std:
    - 0.5
  random_zoom_out:
    side_range:
    - 1
    - 1.5
    p: 0.7
    fill: 255

  c: 1
  h: 64
  w: 256

  random_affine:
    degrees: 5
    fill: 255

datasets:
- "data/words_train_df_processed.csv"

dataloader:
  batch_size: 160
  num_workers: 16
  pin_memory: True