max_seq_len: 0

train_dataset:
  preprocessor:
    normalize:
      mean:
      - 0.5
      std:
      - 0.5

  dataset_parts:
    - annotations_path: "data/train_annotations.txt"
      images_dir: "iam_words"

  dataloader:
    batch_size: 1024
    num_workers: 0
    pin_memory: True

val_dataset:
  preprocessor:
    normalize:
      mean:
      - 0.5
      std:
      - 0.5

  dataset_parts:
    - annotations_path: "data/val_annotations.txt"
      images_dir: "iam_words"

  dataloader:
    batch_size: 512
    num_workers: 0
    pin_memory: True

test_dataset:
  preprocessor:
    normalize:
      mean:
      - 0.5
      std:
      - 0.5

  dataset_parts:
    - annotations_path: "data/test_annotations.txt"
      images_dir: "iam_words"

  dataloader:
    batch_size: 512
    num_workers: 0
    pin_memory: True