name: "words"

preprocessor:
  normalize:
    mean:
    - 0.5
    std:
    - 0.5
  random_zoom_out:
    side_range:
    - 1
    - 1.5
    p: 0.7
    fill: 255

  c: 1
  h: 64
  w: 256

  random_affine:
    degrees: 5
    fill: 255

annotations_path: "/content/gan.iam.tr_va.gt.filter27"
images_dir: "/content/word_stylist_images/generated_images/images/"

max_seq_len: 8

dataloader:
  batch_size: 16
  num_workers: 0
  pin_memory: True