max_seq_len: 8

train_dataset:
  preprocessor:
    normalize:
      mean:
      - 0.5
      std:
      - 0.5

  dataset_parts:
    - annotations_path: "data/gan.iam.tr_va.gt.filter27"
      images_dir: "data/mock_dataset"

  dataloader:
    batch_size: 512
    num_workers: 0
    pin_memory: True

test_dataset:
  preprocessor:
    normalize:
      mean:
      - 0.5
      std:
      - 0.5

  dataset_parts:
    - annotations_path: "data/gan.iam.test.gt.filter27"
      images_dir: "data/mock_dataset"

  dataloader:
    batch_size: 512
    num_workers: 0
    pin_memory: True